#!/bin/bash

success () {
	echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning () {
	echo "$(tput setaf 1)$1$(tput sgr0)"
}

newline () {
	echo ""
}

apt_pkg_req () {
	APT_CHK=$(dpkg-query -W --showformat='${Status}\n' $1|grep "install ok installed")
	if [ "" == "$APT_CHK" ]; then
		true
	else
		false
	fi
}

success "Picade Updater. Version 1.1"

newline

FIRMWARE=${1:-picade.hex}

echo "Checking for required packages..."

if apt_pkg_req "avrdude"; then
    echo "- avrdude missing, installing..."
    sudo apt-get update
    sudo apt-get --force-yes --yes install avrdude
else
    success "- avrdude already installed."
fi

newline

success "Updating should continue automatically."
success "If not, press reset on your Picade."

echo ""

if [ -e /dev/ttyACM0 ]; then
	stty -F /dev/ttyACM0 1200
	while [ -e /dev/ttyACM0 ];
	do
		sleep 0.01
	done
fi

while [ ! -e /dev/ttyACM0 ];
do
	sleep 0.01
done

sleep 0.5

avrdude -D -c avr109 -p m32u4 -P /dev/ttyACM0 -U flash:w:$FIRMWARE
